### ISSUE TITLE
Speed improvement: One single tooltip shared among all user-markers

### ISSUE THREAD

**Issue by lordfuoco** [pulilab/vue-people#117]
Currently the each MapMaarker instantiate a l-tooltip inside.
This is suboptimal since we always show only one tooltip at a time.

What is needed is to remove the l-tooltip from every marker, add one `l-layer-group` inside the `l-map` with inside a 'general tooltip' and display that tooltip on marker over on the correct coordinates.

This will reduce the amount of drawn element in the dom and speed up the page / responsiveness of the map.

This needs to be done only for people markers / tooltip and not for meetup ones.

**Comment by flurmbo** [comment]
I'd like to try this one if that's okay!

**Comment by lordfuoco** [comment]
@flurmbo go on without worries! Let me know if you need anything

**Comment by flurmbo** [comment]
Hey @lordfuoco, I'm having some issues setting up a development environment. A lot seems to be going wrong, so I'll just summarize some of the errors!

- When I point my browser to localhost:3000 I get a "NuxtServerError Request failed with status code 504" 

- HPM logs that  "error occured while trying to proxy request /api/tags from localhost:3000 to https://localhost/ and similar messages for the rest of the api.

- nginx says that "ssl_stapling" is ignored, no OCSP responder URL in the certificate "/etc/letsencrypt/cert.pem"

I copied the dummy certs to the nginx/certs folder and otherwise tried following the instructions in the readme. I am using Windows 7.

Any help getting this to run would be greatly appreciated[ the Vue code looks really cool. I am completely new to nuxt, docker and SSL certificates, so maybe I'm missing something obvious!

**Comment by lordfuoco** [comment]
Hi @flurmbo this is a tipical error that occurs when the frontend dev server proxy can't reach the backend.

Please verify that your docker is running by going to your browser at: localhost and localhost/admin

Docker logs can be accessed by the command: docker-compose logs run in the project root folder

Did you run the migrations?

Also now I am on the go but when I reach the office I will update the how to contribute guide on how to config and access the admin console (so that one can login with GitHub and create a pin) and maybe add a dummy db with few pins

**Comment by flurmbo** [comment]
@lordfuoco Thanks for the help, unfortunately I'm still having trouble. If I run "docker ps" all the containers seem to be running, but when I point my browser to localhost/admin I get a 404. I ran the migrations and it says "no migrations to apply", I've also made a superuser. Is there anything I need to change in django/.env other than setting DEBUG to True?

**Comment by lordfuoco** [comment]
@flurmbo this make me think that ngninx container has a problem / is not correctly running.

Try to check with docker-compose logs nginx
Sorry for the messy dev experience, I will update the readme once again with the debug=true

Here is late so I will be able to answer only tomorrow but write with any update

**Comment by flurmbo** [comment]
No problem, it's been fun trying out docker. If the problem is with nginx, then this warning might have something to do with it:

nginx_1 [warn] 1#1: "ssl_stapling ignored, no OCSP responder URL in the certificate "/etc/letsencrypt/cert.pem"

**Comment by lordfuoco** [comment]
I am taking this

**Comment by flurmbo** [comment]
Thanks! Looks good
