### ISSUE TITLE
The counter in the bottom left doesn't count anymore

### ISSUE THREAD

**Issue by gustojs** [pulilab/vue-people#56]
Previously, when I zoomed in on the map, the counter in the bottom left updated with the numbers from the visible area of the map. Now, after switching to multiple-user pins, it doesn't update anymore.

**Comment by lordfuoco** [comment]
@gustojs Hi! So this is actually intentional ( #36 ) and now the legend is just a count divided by role;

for the following reasons:
- the clusters already give (and sometimes even more precisely ) an information about the amount of pins in an area
- The hover to put on focus only that role does not make sense with clusters
- It was a huge drain on performance to check pin by pin if they were inside the 'bounding area'

Let me know what you think about this reasoning!

This issue make me feel that we need a proper changelog from now on, or maybe even a release system where we state the changes. We are proceeding fast after all!

**Comment by lordfuoco** [comment]
@gustojs closing this, feel free to reply here if you have any insight
