### ISSUE TITLE
Vue Repositories not showing up in listing

### ISSUE THREAD

**Issue by rdelga80** [pulilab/vue-people#85]
I have two visible ones that aren't showing up.

https://vuepeople.org/user/774/

**Comment by lordfuoco** [comment]
I think this is related to #80 could you confirm that your repo is a Vue repo but do not use Vue SFC?

**Comment by rdelga80** [comment]
This is one of my repos, it's Vue SFC (the other is the same):

https://github.com/rdelga80/PickUrArnie2

**Comment by gustojs** [comment]
I starred it, so it may show up now, please check it. There was a change (requested by me) so that 0-star libraries don't show up, since they are mostly forks or work in progress.

If you have a repository that you think would be helpful for others, I'd suggest sharing it on social media and providing some description of what it actually does in the README.

Alternative solution may be to provide a form on VuePeople, where developers can link their missing repositories that don't have any stars or `.vue` files but they want them visible anyways.

**Comment by rdelga80** [comment]
They're just projects I've built, so I don't think there'd be any reason other people would star it.

That one is showing up, at least. I'll ask someone else to star the other one I have. Thanks.
